apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: development.app.192.168.49.2.nip.io  
    http:
      paths:
      - path: /
        backend:
          serviceName: development-java-hello-world-svc
          servicePort: 8102
  
      