namePrefix: development-
commonLabels:
  variant: development
commonAnnotations:
  note: Hello, I am running in development environment!
namespace: development
bases:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
resources:
- ingress.yaml
images:
- name: dennydgl1/java-hello-world
  newName: docklyear/java-hello-world
  newTag: "my-feature-1"
configMapGenerator:
 - behavior: merge
   name: java-hello-world-cm
   envs: 
    - env.properties
   files:
    - application.yaml 
